---
title: "Home"
---

#About DataFest

####DataFest is a nationally-coordinated undergraduate competition in which teams of up to 5 students work over a weekend to extract insight from a rich and complex data set. Previous years’ data sets have included crime data from the LAPD, dating data from eHarmony, and energy use data from GridPoint. This year’s data set will be revealed at the opening of the event on Friday evening. At the conclusion of the competition, each team will have 5 minutes to make a presentation to a panel of judges. Each panel of judges will select a team for the “Best in Group” prize, and the entire group of judges will determine a “Best in Show” prize. Other additional prizes may be awarded.

####The mission of DataFest is to expose undergraduate students to challenging questions with immediate real-world significance that can be addressed through data analysis. By working in teams, students with varying skill sets will combine their efforts and expand their collective data analysis horizons. Interaction among students, as well as with outside consultants will promote the sense that data analysis is a dynamic, engaging, and vibrant part of our society, as well as a realistic, practical, and fun career path.

#Specific Event Details
???


#The CSUC will take place: 

Start: Friday, April 27, 2018, #TIME

Finish: Sunday, April 29, 2018, #TIME

Venue:  #? 

###Who is eligible to compete?
All CSU Chico undergraduate students are eligable to compete. 

###What do I need to compete?
All you need is a laptop with tools for data analysis (there is no limitation on which software you use) and enthusiasm for data.

###What can I win?
Prizes, fame, glory, or some combination thereof

###What are the rules of the competition?
The rules are very simple:
-No more than five students members per team.  
-Team members can come and go as they please but all work has to be done on-site. A steady supply of food, beverage, and snacks make it more inviting to stay.  
-It’s a competition, but a friendly one, so collaboration between teams is not only allowed but highly encouraged. Official DataFest consultants (grad students, faculty, etc.) will also be around throughout the weekend to help with any questions you might have. However you can’t have outside help.  

###Do we have to stay the entire time?
No. You may come and go as you please. However, you are not allowed to work on the project except while you are on ASA DataFestTM grounds, and at least 3 members of your team must attend the introduction.

##Where can I sign up?
Right here!: https://docs.google.com/forms/d/e/1FAIpQLSf6lrnab-gm-ds5xsi8Ss5j3E-ZTUc0ipSNQYOEvSzRbkoKhw/viewform or the sign up link up top. 

###Any questions can ask: 
